# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.6.x version
  - 5.6

env:
  - mysql

services:
  - mysql

before_script:
  # Manual Install
  - sudo apt-get --assume-yes install apache2 libapache2-mod-php5 php5-mcrypt php5-mysqlnd php5-gd php-pear php-apc php5-curl curl lynx-cur libbz2-dev libssl-dev python python-dev libmysqlclient-dev python-pip expect default-jre libxml2-dev software-properties-common libcurl4-gnutls-dev gdebi-core wget tree
  # pip
  - sudo pip install --upgrade pip pycrypto urllib3
  - sudo pip install simple-crypt MySQL-python pjson
  # other dependencies
  - printf "[Dolphin]\nSALT=test123\nPEPPER=test456\nMASTER=travis\nAMAZON=travis\n" > config/.salt
  # Install apache, PHP, and supplimentary programs. curl and lynx-cur are for debugging the container.
  - sudo a2enmod actions
  - sudo a2enmod php5
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/allow_url_include = Off/allow_url_include = On/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/;   extension=msql.so/extension=mysql.so/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/; extension_dir = \"./\"/extension_dir = \"./\"/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/;   extension=msql.so/extension=mysqli.ddl/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/;include_path = \".:/usr/share/php\"/include_path = \".:/usr/share/php\"" /etc/php5/apache2/php.ini
  
  - sudo cp /etc/php5/apache2/php.ini /etc/php5/cli/php.ini
  - sudo cat /etc/php5/apache2/php.ini
  - sudo tree /etc/php5
  - sudo php --ini
  #- sudo service apache2 restart
  # dolphin repos
  - git clone https://github.com/UMMS-Biocore/dolphin-tools.git /home/travis/build/dolphin_tools
  - git clone https://github.com/UMMS-Biocore/dolphin-bin.git /home/travis/build/dolphin-bin
  - git clone https://github.com/UMMS-Biocore/dolphin-genome-data.git /home/travis/build/dolphin-genome-data
  - ls -lash
  - sudo mkdir -p /home/travis/build/pub /home/travis/build/logs tmp/files tmp/logs /home/travis/build/travisrun1
  - sudo chmod -R 777 /home/travis/build/pub /home/travis/build/logs /home/travis/build/travisrun1 ./*
  - sudo sed -i 's/dolphin\/api/dolphin\/public\/api/g' /home/travis/build/dolphin_tools/default_params/config.ini
  - sudo ln -s $(pwd) /var/www/dolphin
  - sudo chown -R www-data:www-data *
  # Manually set up the apache environment variables
  - sudo mysql -u root -e "CREATE USER 'myproject'@'localhost' IDENTIFIED BY 'mypass'"
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'myproject'@'localhost' WITH GRANT OPTION;"
  - PATH=$PATH:/home/travis/build/dolphin-bin
  # update database
  - sudo gzip -d db/biocoredb.sql.gz
  - sudo mysql -e "CREATE DATABASE biocore;" -uroot
  - sudo mysql -e "CREATE USER 'bioinfo'@'localhost' IDENTIFIED BY 'bioinfo2013'; GRANT ALL ON *.* TO 'bioinfo'@'localhost';" -uroot
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/biocoredb.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_07_22_consolidated_1.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_08_31_wkeylist.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_10_16_ngs_createtables.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_10_27_tablegen_sidebar.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_11_05_user_group_requests.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_11_16_newuser.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_02_08_email_update.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_03_07_delete_runs.sql
  - sudo mysql -e "use biocore; UPDATE ngs_samples set samplename = name;" -uroot
  - sudo mysql -e "use biocore; INSERT INTO amazon_credentials ( aws_access_key_id, aws_secret_access_key, bucket ) VALUES ( 'test_access', 'test_secret', 'test_bucket' );" -uroot
  - sudo mysql -e "use biocore; INSERT INTO ngs_organism (organism) VALUES ('human'); UPDATE ngs_samples SET organism_id = 1;" -uroot
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_05_09_aws.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_05_11_rechecksum.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_07_01_aws.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_07_07_salt.sql
  - sudo mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_08_02_travisuser.sql
  - curl http://localhost/index.php
  - curl http://localhost/dolphin/phpinfo.php
  - curl http://localhost/dolphin/public/api/service.php
  - ps -ef
  - sudo cat /etc/hosts
 
script:
  #	ajax - initial mapping
  - phpunit unitTesting/ngsimport_unittest.php
  - phpunit unitTesting/ajax/ngsalterdb_unittest.php
  #	Run workflow
  - python unitTesting/travis_test.py
  - cd scripts
  - mkdir -p ../tmp/logs/run4
  #- sudo python dolphin_wrapper.py -r 4 -c Travis
  #	ajax
  #- phpunit unitTesting/ajax/tablegenerator_unittest.php
  #- phpunit unitTesting/ajax/statquerydb_unittest.php
  #- phpunit unitTesting/ajax/sessionrequests_unittest.php
  #- phpunit unitTesting/ajax/profiledb_unittest.php
  #- phpunit unitTesting/ajax/ngsquerydb_unittest.php
  #- phpunit unitTesting/ajax/ngsfastlanedb_unittest.php
  #- phpunit unitTesting/ajax/ngs_tables_unittest.php
  #- phpunit unitTesting/ajax/kill_pid_unittest.php
  #- phpunit unitTesting/ajax/initialmappingdb_unittest.php
  #- phpunit unitTesting/ajax/dolphinfuncs_unittest.php
  #- phpunit unitTesting/ajax/dataservice_unittest.php
  #- phpunit unitTesting/ajax/datajobs_unittest.php
  #- phpunit unitTesting/ajax/dataerrorlogs_unittest.php
  #- phpunit unitTesting/ajax/dashboardquerydb_unittest.php
  #- phpunit unitTesting/ajax/browse_edit_unittest.php
  #- phpunit unitTesting/ajax/admindashboardquerydb_unittest.php
  #- phpunit unitTesting/ajax/adminstatquerydb_unittest.php
  #	api
  #- phpunit unitTesting/api/funcs_unittest.php

after_script:
  - mysql -e "show databases;" -uroot
  - mysql -e "use biocore; show tables;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_samples;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_lanes;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_experiment_series;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_dirs;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_runlist;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_runparams;" -uroot
  - mysql -e "use biocore; SELECT * FROM report_list;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_createdtables;" -uroot
  - mysql -e "use biocore; SELECT * FROM amazon_credentials;" -uroot
  - mysql -e "use biocore; SELECT * FROM groups;" -uroot
  - mysql -e "use biocore; SELECT * FROM user_group_requests;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_wkeylist;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_organism;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_fastq_files" -uroot
  - mysql -e "use biocore; SELECT * FROM galaxy_runs" -uroot
  - mysql -e "use biocore; SELECT * FROM users" -uroot
  - mysql -e "use biocore; SELECT * FROM jobs" -uroot
  - mysql -e "use biocore; SELECT * FROM services" -uroot
  - mysql -e "use biocore; SELECT * FROM jobstats" -uroot
  - mysql -e "use biocore; SELECT * FROM workflows" -uroot
  - mysql -e "use biocore; SELECT * FROM service_run" -uroot
  - mysql -e "use biocore; SELECT * FROM jobstats" -uroot
  
