# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  #- 5.4
  # aliased to a recent 5.5.x version
  #- 5.5
  # aliased to a recent 5.6.x version
  - 5.6

env:
  - mysql

services:
  - mysql

before_script:
  - pwd
  # initial set-up
  - sudo apt-get update
  # dolphin repos
  - git clone https://github.com/UMMS-Biocore/dolphin-tools.git /home/travis/build/dolphin_tools
  - git clone https://github.com/UMMS-Biocore/dolphin-bin.git /home/travis/build/dolphin-bin
  - git clone https://github.com/UMMS-Biocore/dolphin-genome-data.git /home/travis/build/dolphin-genome-data
  - mkdir /home/travis/build/pub
  - mkdir /home/travis/build/logs
  # Install apache, PHP, and supplimentary programs. curl and lynx-cur are for debugging the container.
  - sudo apt-get -y install apache2 libapache2-mod-php5 python python-dev software-properties-common libcurl4-gnutls-dev gdebi-core
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  # updates
  - sudo apt-get -y update
  # Enable apache mods.
  - sudo a2enmod php5
  - sudo a2enmod rewrite
  # Update the PHP.ini file, enable <? ?> tags and quieten logging.
  - sudo sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php5/apache2/php.ini
  - sudo sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php5/apache2/php.ini
  # Manually set up the apache environment variables
  - PATH=$PATH:/usr/local/bin/dolphin-bin
  - APACHE_RUN_USER="www-data"
  - APACHE_RUN_GROUP="www-data"
  - APACHE_LOG_DIR="/var/log/apache2"
  - APACHE_LOCK_DIR="/var/lock/apache2"
  - APACHE_PID_FILE="/var/run/apache2.pid"
  - DOLPHIN_PARAMS_SECTION=Travis
  - sudo ln -s $(pwd) /var/www/dolphin
  - sudo cp /var/www/dolphin/unitTesting/000-default.conf /etc/apache2/sites-available/000-default.conf
  # pip
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade pycrypto
  - sudo pip install simple-crypt
  - sudo pip install MySQL-python
  #- sudo apt-get install python-mysqldb 
  # update database
  - gzip -d db/biocoredb.sql.gz
  - mysql -e "CREATE DATABASE biocore;" -uroot
  - mysql -e "CREATE USER 'bioinfo'@'localhost' IDENTIFIED BY 'bioinfo2013'; GRANT ALL ON *.* TO 'bioinfo'@'localhost';" -uroot
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/biocoredb.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_07_22_consolidated_1.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_08_31_wkeylist.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_10_16_ngs_createtables.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_10_27_tablegen_sidebar.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2015_11_05_user_group_requests.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_03_07_delete_runs.sql
  - mysql -e "use biocore; UPDATE ngs_samples set samplename = name;" -uroot
  - mysql -e "use biocore; INSERT INTO amazon_credentials ( aws_access_key_id, aws_secret_access_key, bucket ) VALUES ( 'test_access', 'test_secret', 'test_bucket' );" -uroot
  - mysql -e "use biocore; INSERT INTO ngs_organism (organism) VALUES ('human'); UPDATE ngs_samples SET organism_id = 1;" -uroot
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_05_09_aws.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_05_11_rechecksum.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_07_01_aws.sql
  - mysql --user=bioinfo --password=bioinfo2013 biocore < db/2016_07_07_salt.sql
  # other dependencies
  - printf "[Dolphin]\nSALT=test123\nPEPPER=test456\nMASTER=travis\nAMAZON=travis\n" > config/.salt
  - cat config/.salt
  - sudo service apache2 restart
  - service --status-all
 
script:
  #	ajax - initial mapping
  - phpunit unitTesting/ngsimport_unittest.php
  - phpunit unitTesting/ajax/ngsalterdb_unittest.php
  #	Run workflow
  - cd scripts
  - mkdir -p ../tmp/logs/run4
  - python dolphin_wrapper.py -r 4 -c Travis
  #	ajax
  #- phpunit unitTesting/ajax/tablegenerator_unittest.php
  #- phpunit unitTesting/ajax/statquerydb_unittest.php
  #- phpunit unitTesting/ajax/sessionrequests_unittest.php
  #- phpunit unitTesting/ajax/profiledb_unittest.php
  #- phpunit unitTesting/ajax/ngsquerydb_unittest.php
  #- phpunit unitTesting/ajax/ngsfastlanedb_unittest.php
  #- phpunit unitTesting/ajax/ngs_tables_unittest.php
  #- phpunit unitTesting/ajax/kill_pid_unittest.php
  #- phpunit unitTesting/ajax/initialmappingdb_unittest.php
  #- phpunit unitTesting/ajax/dolphinfuncs_unittest.php
  #- phpunit unitTesting/ajax/dataservice_unittest.php
  #- phpunit unitTesting/ajax/datajobs_unittest.php
  #- phpunit unitTesting/ajax/dataerrorlogs_unittest.php
  #- phpunit unitTesting/ajax/dashboardquerydb_unittest.php
  #- phpunit unitTesting/ajax/browse_edit_unittest.php
  #- phpunit unitTesting/ajax/admindashboardquerydb_unittest.php
  #- phpunit unitTesting/ajax/adminstatquerydb_unittest.php
  #	api
  #- phpunit unitTesting/api/funcs_unittest.php

after_script:
  - mysql -e "show databases;" -uroot
  - mysql -e "use biocore; show tables;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_samples;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_lanes;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_experiment_series;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_dirs;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_runlist;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_runparams;" -uroot
  - mysql -e "use biocore; SELECT * FROM report_list;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_createdtables;" -uroot
  - mysql -e "use biocore; SELECT * FROM amazon_credentials;" -uroot
  - mysql -e "use biocore; SELECT * FROM groups;" -uroot
  - mysql -e "use biocore; SELECT * FROM user_group_requests;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_wkeylist;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_organism;" -uroot
  - mysql -e "use biocore; SELECT * FROM ngs_fastq_files" -uroot
  - mysql -e "use biocore; SELECT * FROM galaxy_runs" -uroot
  - mysql -e "use biocore; SELECT * FROM users" -uroot
  - mysql -e "use biocore; SELECT * FROM jobs" -uroot
  - mysql -e "use biocore; SELECT * FROM services" -uroot
  - mysql -e "use biocore; SELECT * FROM jobstats" -uroot
  - mysql -e "use biocore; SELECT * FROM workflows" -uroot
  - mysql -e "use biocore; SELECT * FROM service_run" -uroot
  - mysql -e "use biocore; SELECT * FROM jobstats" -uroot
  
